/*******************************************************************************

ItemSelection is a JFrame that asks the user to choose an item to select.

////////////////////////////////////////////////////////////////////////////////

INPUTS

1.	ItemSelection - Item Radio Button Choice, Quantity Combo Box, Continue/Exit Button

////////////////////////////////////////////////////////////////////////////////

OUTPUTS

1.	ItemSelection - Item Radio Buttons Text, Quantity Combo Box Values(Visible or Hidden)

*///////////////////////////////////////////////////////////////////////////////

package ThePickleApp;

import static ThePickleApp.ThePickleMafiaApp.oData;
import static ThePickleApp.ThePickleMafiaApp.items;
import javax.swing.JRadioButton;



public class ItemSelection extends javax.swing.JFrame {

    /**
     * Creates new form ItemSelection
     */
    public ItemSelection() {
        initComponents();
        
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
        
        // if part of a combo order, disables the quantity combo box
        if (oData.getStep() > 0){
            ComboBoxQty.setEnabled(false);
        } else {
            ComboBoxQty.setEnabled(true);
        }
        
        int Cat = oData.getCatNum();
        // displays items depending on which category has been selected
        switch (Cat) {
            case 2:
                jRadioButton1.setText(items.get(0));
                jRadioButton2.setText(items.get(1));
                jRadioButton3.setText(items.get(2));
                jRadioButton4.setText(items.get(3));
                break;
            case 3:
                jRadioButton1.setText(items.get(4));
                jRadioButton2.setText(items.get(5));
                jRadioButton3.setText(items.get(6));
                jRadioButton4.setText(items.get(7));
                break;
            case 4:
                jRadioButton1.setText(items.get(8));
                jRadioButton2.setText(items.get(9));
                jRadioButton3.setText(items.get(10));
                jRadioButton4.setText(items.get(11));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        ComboBoxQty = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Please Select an Item:");

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        jRadioButton4.setText("jRadioButton4");

        ComboBoxQty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Continue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Qty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(ComboBoxQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Exit Button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    // handle method adds the selected item to the summary
    private void handle(JRadioButton radioButton) {
        String itemText = radioButton.getText();
        String[] parts = itemText.split("-");  // Separate item and price by dash
        if (parts.length == 2) {
            String itemName = parts[0].trim();
            int itemPrice = Integer.parseInt(parts[1].trim());
            oData.setItem(itemName);
            oData.setPrice(itemPrice);
        }
        
        // if statement determines whether the item info is part of a combo order or an independent item
        if (oData.getStep() > 0){
            // Add item to combo
            oData.addToCombo();
        } else {
            oData.setQty(Integer.parseInt(ComboBoxQty.getSelectedItem().toString()));
            // Add item to order summary
            oData.addItemToSummary();
        }
        

        // Check if we've reached the last category (4 categories: burger, side, drink, and a final step)
        if (oData.getStep() > 0 && oData.getStep() < 3) {
            // Proceed to the next category menu
            MenuSelection ms = new MenuSelection();
            ms.handleComboMealSelection();
            dispose();
        } else {
            // If all categories are done, show the order summary
            oData.addComboToSummary();
            dispose();
            OrderSummary os = new OrderSummary();
            os.setVisible(true);
            oData.resetCombo();
        }
    }

    // Continue Button / Displays Order Summary
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        // Handle item selection and navigate accordingly
        if (jRadioButton1.isSelected()) {
            handle(jRadioButton1);
        } else if (jRadioButton2.isSelected()) {
            handle(jRadioButton2);
        } else if (jRadioButton3.isSelected()) {
            handle(jRadioButton3);
        } else if (jRadioButton4.isSelected()) {
            handle(jRadioButton4);
        } else {
            // If no item is selected, display an alert
            System.out.println("No item selected.");
                javax.swing.JOptionPane.showMessageDialog(this, "Please select an item.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxQty;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
