/*******************************************************************************

MenuSelection is a JFrame that asks the user to choose a menu to select an item from.
There is also an option for a combo, in which the application will then iterate through each of the menus, allowing an item selection from each one.

////////////////////////////////////////////////////////////////////////////////

INPUTS

1.	MenuSelection - Menu Radio Button Choice, Continue/Exit Button

*///////////////////////////////////////////////////////////////////////////////

package ThePickleApp;

import static ThePickleApp.ThePickleMafiaApp.oData;



public class MenuSelection extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuSelection
     */
    public MenuSelection() {
        initComponents();
        
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setText("Combo Meal");

        jRadioButton2.setText("Burgers");

        jRadioButton3.setText("Sides");

        jRadioButton4.setText("Drinks");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Continue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Please Select a Category:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Exit Button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Continue Button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if (jRadioButton1.isSelected()) {
            // Combo Meal selected
            oData.setCombo();
            oData.setStep(0);  // Reset the step when Combo Meal is selected
            oData.setCatNum(1);
            handleComboMealSelection();  // Continue the Combo Meal flow
        } else {
            // Individual category selected
            oData.setStep(-1);  // Invalidate the step to avoid Combo Meal flow

            if (jRadioButton2.isSelected()) {
                // Handle Burgers category
                oData.setCatNum(2);  // Set category to Burgers
                navigateToItemSelection();
            } else if (jRadioButton3.isSelected()) {
                // Handle Sides category
                oData.setCatNum(3);  // Set category to Sides
                navigateToItemSelection();
            } else if (jRadioButton4.isSelected()) {
                // Handle Drinks category
                oData.setCatNum(4);  // Set category to Drinks
                navigateToItemSelection();
            } else {
                // Handle no selection
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a category.");  // Warning message, prompts the user to choose a category
            }
        }    
    }//GEN-LAST:event_jButton2ActionPerformed

    // handleComboMealSelection checks to see which menu of the combo selection is next to display
    public void handleComboMealSelection() {

        // Step 1: Show Burger menu after Combo meal
        if (oData.getStep() == 0) {
            oData.setCatNum(2);  // Set category to Burgers
            oData.incrementStep(1);  // Move to the next step
            navigateToItemSelection();  // Navigate to the Burger menu
        } 
        // Step 2: Show Sides menu after Burger selection
        else if (oData.getStep() == 1) {
            oData.setCatNum(3);  // Set category to Sides
            oData.incrementStep(1);  // Move to the next step
            navigateToItemSelection();  // Navigate to the Sides menu
        } 
        // Step 3: Show Drinks menu after Sides selection
        else if (oData.getStep() == 2) {
            oData.setCatNum(4);  // Set category to Drinks
            oData.incrementStep(1);  // Move to the next step
            navigateToItemSelection();  // Navigate to the Drinks menu
        } 
        // All categories selected, show OrderSummary
        else {
            displayOrderSummary();  // All steps completed, show the summary
        }
    }
    
    // navigateToItemSelection method closes window and opens the ItemSelection screen
    private void navigateToItemSelection() {
        dispose();
        ItemSelection is = new ItemSelection();
        is.setVisible(true);
    }

    // displayOrderSummary method closes window and opens the OrderSummary screen
    private void displayOrderSummary() {
        dispose();
        OrderSummary os = new OrderSummary();
        os.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
